### ISSUE TITLE
[iOS] Are there any plans to add Privacy Manifests?

### ISSUE THREAD

**Issue by StatusCode200** [flutter-ml/google_ml_kit_flutter#584]
Apple recently announced that starting in Spring 2024, apps will be required to include more privacy-related reasoning for "third-party SDKs." This includes providing details in privacy manifests about data use by these SDKs. You can read more about this requirement on the Apple Developer website: [Describing Data Use in Privacy Manifests](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests?language=objc)

Many popular Flutter plugins, such as shared_preferences, have already implemented these manifests. You can see an example of such a manifest in the shared_preferences plugin here: [PrivacyInfo.xcprivacy](https://github.com/flutter/packages/blob/main/packages/shared_preferences/shared_preferences_foundation/darwin/Resources/PrivacyInfo.xcprivacy)

Given these upcoming requirements, it's important to note that even libraries that do not collect privacy-policy-relevant information may need to include an empty PrivacyInfo.xcprivacy file to avoid potential rejection.

Thank you for your attention to this matter.

**Comment by ShuheiSuzuki-07** [comment]
MLKit seems to be supported by
https://github.com/googlesamples/mlkit/issues/795

I am sure the flutter plugin will support it after the above release.

It would be nice to have some kind of announcement.

**Comment by fbernaly** [comment]
I have been very busy with my job and personal life. Contributions are welcome. Send your PRs and I will review them ASAP. So far I do not have an ETA for all the new features.

**Comment by ShuheiSuzuki-07** [comment]
The latest MLKit has been released.
https://github.com/googlesamples/mlkit/issues/795#issuecomment-2064955148

**Comment by fbernaly** [comment]
@ShuheiSuzuki-07 : I do not have an ETA for this new feature. Feel free to send your PR with your contribution.

**Comment by pongloongyeat** [comment]
Seems like there was a recent release on pub which included the commits to bump MLKit [deps](https://github.com/flutter-ml/google_ml_kit_flutter/pull/617/files#diff-bd718fe51db576b783a23637e7add1128a64387ca48f3bd70756fe33b9192f2e). However, it seems like I'm still getting an outdated version of the dependencies. Am I missing something?

pubspec.yaml:
```yaml
environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_face_detection: ^0.10.1
```

<img width="1440" alt="image" src="https://github.com/flutter-ml/google_ml_kit_flutter/assets/31680656/f1bddacf-07f4-4dda-b093-bbc4ce0cf1b3">

This also causes our app to receive the privacy manifest warning, which I believe is caused by GoogleToolboxForMac as per [this comment](https://github.com/googlesamples/mlkit/issues/795#issue-2195781220)

**Comment by ShuheiSuzuki-07** [comment]
@pongloongyeat 
Thanks to the efforts of the author and contributors, the latest version of this plugin was released a few hours ago. If you use it, the problem with GoogleToolBoxForMac should be solved.

Reference:
https://github.com/flutter-ml/google_ml_kit_flutter/pull/621
https://developers.google.com/ml-kit/release-notes?hl=ja

![image](https://github.com/flutter-ml/google_ml_kit_flutter/assets/118415919/3cf94da0-cc47-4525-85de-03bf19ed0c9c)

**Comment by fbernaly** [comment]
Confirm if with the latest release this issue is fixed. Then close the issue.

**Comment by pongloongyeat** [comment]
Can confirm that the latest release does indeed come with the updated `GoogleToolboxForMac`. However, I'm still getting the privacy manifest issue on an empty Flutter project with just `google_mlkit_face_detection: ^0.11.0` whereas a completely empty Flutter project does not cause any problems. Could this be related to a [bug with AppStore Connect](https://github.com/flutter/flutter/issues/145269#issuecomment-2070221423)?.

Looking through each of Runner's framework's privacy manifests very briefly, it seems like all dependencies except Runner itself declares a privacy manifest file. To that end, I'm not sure if the issue is on this package or with Flutter itself.

**Comment by fbernaly** [comment]
Since an empty project works, I would recommend to create a new project with the latest Flutter plugin and the copy the `lib` folder and yaml file of your old project into that new project and then compile and see if the new Xcode configuration of that new Flutter template works.
